// <auto-generated />
namespace majig.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _UserIdNum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_UserIdNum));
        
        string IMigrationMetadata.Id
        {
            get { return "201810180529422__User.IdNum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
